# Generated by Django 4.0.3 on 2022-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Strategy name')),
                ('long_limit', models.PositiveSmallIntegerField(verbose_name='Shares amount limit to store')),
                ('short_limit', models.SmallIntegerField(verbose_name='Shares amount limit to borrow')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
