# Generated by Django 5.0.6 on 2024-06-11 17:28

import django.db.models.deletion
import src.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.SlugField(max_length=275, primary_key=True, serialize=False)),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('60m', '60m'), ('90m', '90m'), ('1h', '1h'), ('1d', '1d'), ('5d', '5d'), ('1wk', '1wk'), ('1mo', '1mo'), ('3mo', '3mo')], max_length=3)),
                ('strategies', models.JSONField()),
                ('logs', src.utils.fields.DataFrameField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'get_latest_by': '-update_time',
                'order_with_respect_to': 'portfolio',
            },
        ),
    ]
