# Generated by Django 5.0.6 on 2024-06-11 17:28

import django.db.models.deletion
import src.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('fund', 'Mutual Fund'), ('futures', 'Futures'), ('forex', 'Currency'), ('index', 'Index'), ('bond', 'Bond'), ('option', 'Option'), ('crypto', 'Crypto')], default='stock', max_length=7)),
                ('exchange', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_name', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='America/New_York', max_length=32)),
                ('country', models.CharField(default='USA', max_length=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('type', 'symbol', 'name'),
                'get_latest_by': '-symbol',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.SlugField(max_length=21, primary_key=True, serialize=False)),
                ('ohlcv', src.utils.fields.DataFrameField()),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('2m', '2m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('60m', '60m'), ('90m', '90m'), ('1h', '1h'), ('1d', '1d'), ('5d', '5d'), ('1wk', '1wk'), ('1mo', '1mo'), ('3mo', '3mo')], max_length=3)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'ordering': ('-update_time',),
                'get_latest_by': '-update_time',
                'unique_together': {('stock', 'timeframe')},
            },
        ),
    ]
